
{{- if .Values.cloudProxy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airbyte-cloud-proxy
  labels:
    {{- include "airbyte.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.cloudProxy.replicaCount }}
  selector:
    matchLabels:
      airbyte: cloud-proxy
  template:
    metadata:
      labels:
        airbyte: cloud-proxy
      {{- if .Values.cloudProxy.podAnnotations }}
      annotations:
        {{- include "common.tplvalues.render" (dict "value" .Values.cloudProxy.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "airbyte.serviceAccountName" . }}
      containers:
        - image: {{ include "airbyte.cloudProxyImage" . }}
          name: cloud-sql-proxy
          imagePullPolicy: "{{ .Values.cloudProxy.image.pullPolicy }}"
          command:
          - "/cloud_sql_proxy"
          - "-ip_address_types=PRIVATE"
          - "-log_debug_stdout"
          - "-enable_iam_login"
          - "-instances={{ .Values.cloudProxy.projectId }}:{{ .Values.cloudProxy.region }}:{{ .Values.cloudProxy.instanceName }}=tcp:5432"
          {{- if .Values.cloudProxy.resources }}
          resources: {{- toYaml .Values.cloudProxy.resources | nindent 10 }}
          {{- end }}
          {{- if .Values.webapp.containerSecurityContext }}
          securityContext: {{- toYaml .Values.webapp.containerSecurityContext | nindent 10 }}
          {{- end }}
{{- end }}




